# safeEnchantsOnly is no longer really used,
#   it is configured in the tier.yml
# allowEnchantsPastNormalLevel is no longer
#   really used
# customItemsSpawn determines if mobs can be
#   given custom items
# customItemsOnly determines if custom items
#   are the only things mobs can be given
# customDropChance determines if mobs are given
#   items when customItemsSpawn is set to true
# autoUpdate determines if the plugin should
#   automatically update itself when it finds
#   an update on BukkitDev
# debugOnStartup determines if the plugin should
#   print out information to a debug file when
#   the server is starting up
options:
  safeEnchantsOnly: true
  allowEnchantsPastNormalLevel: true
  customItemsSpawn: false
  customItemsOnly: false
  customDropChance: 0.05
  autoUpdate: false
  debugOnStartup: false
# spawnEgg 禁止刷怪蛋怪物掉落物品
# spawner 禁止刷怪箱怪物掉落物品
# custom 禁止指令或插件生成的怪物掉落物品
spawnPrevention:
  spawnEgg: true
  spawner: true
  custom: true
# itemNameFormat 确定物品的格式
#   names
# preventMultipleChangesFromSockets 确定是否能从镶嵌物获取多个前缀或后缀
display:
  itemNameFormat: '%tiername%%itemtype%'
  preventMultipleChangesFromSockets: true
# randomLoreEnabled 定义物品是否能从 lore.txt 中获取说明
# randomLoreChance 定义获取说明的几率如果 randomLoreEnabled 是 true
# 定义说明的格式
  tooltips:
    randomLoreEnabled: false
    randomLoreChance: 0.25
    format:
    - "&F类型: %mythicmaterial%"
    - "&7点击铁砧来修复"
# mobSpawnWithItemChance is the global chance
#   for mobs to spawn with an item.
percentages:
  mobSpawnWithItemChance: 0.25
# socketGemsEnabled 定义是否在游戏中生成镶嵌宝石
# socketGemsChance 定义生成镶嵌宝石的几率
# socketGemMaterialIDs 定义镶嵌宝石的原材料列表
# sockettedItemsEnabled determines whether or not items
#   can spawn with sockets
# spawnWithSocketChance is the chance for items to spawn
#   with open sockets
sockets:
  socketGemsEnabled: true
  socketGemsChance: 0.25
  socketGemMaterialIDs:
  - 264
  - 388
  - 399
  sockettedItemsEnabled: true
  spawnWithSocketChance: 0.1
# useAttackerItemInHand determines whether or not
#   the attacking entity's held item should be used
#   when calculating effects
# useAttackerArmorEquipped determines whether or not
#   the attacking entity's equipped armor should be used
#   when calculating effects
# useDefenderItemInHand determines whether or not
#   the defending entity's held item should be used
#   when calculating effects
# useDefenderArmorEquipped determines whether or not
#   the defending entity's equipped armor should be used
#   when calculating effects
effects:
  useAttackerItemInHand: true
  useAttackerArmorEquipped: false
  useDefenderItemInHand: false
  useDefenderArmorEquipped: true
# unidentifiedItemsEnabled determines if unidentified items
#   can spawn in game
# unidentifiedItemChance is the chance for unidentified items
#   to actually spawn in game
# identityTomesEnabled determines if Identity Tomes can spawn
#   in game
# identityTomeChance is the chance for Identity Tomes to
#   actually spawn in game
identification:
  unidentifiedItemsEnabled: true
  unidentifiedItemChance: 0.5
  identityTomesEnabled: true
  identityTomeChance: 0.1
# enabled determines if repairing is enabled on the server
repairing:
  enabled: true
# enabled determines if multiworld support should be enabled
# generate is a list of all worlds where items can be found
# use is a list of all worlds where effects can be applied
worlds:
  enabled: false
  generate:
  - world
  - world_nether
  - world_the_end
  use:
  - world
  - world_nether
  - world_the_end
version: 2.3