main: com.conventnunnery.plugins.mythicdrops.MythicDrops
name: ${project.build.name}
version: ${project.build.version}
authors: [ToppleTheNun,pur3pow3r]
commands:
    mythicdrops:
        description: 生成一个神秘之物.
        aliases: [md,mythic]
        usage: /<command>
permissions:
    mythicdrops.command.spawn:
        description: 允许用户使用 "/md spawn [tier|*] [amount]"
        default: op
    mythicdrops.command.give:
        description: 允许用户使用 "/md give <player> [tier|*] [amount]"
        default: op
    mythicdrops.command.reload:
        description: 允许用户使用 "/md reload"
        default: op
    mythicdrops.command.custom:
        description: 允许用户使用 "/mb custom <player|self> [name] [amount]
        default: op
